### PR TITLE
Fix #214

### LINKED ISSUE #214: Fatal error: exception File "src/ci_opam.ml", line 116, characters 36-42: Assertion failed
In the travis jobs:
- https://travis-ci.org/mirage/mirage-tcpip/jobs/341401840
- https://travis-ci.org/mirage/mirage-tcpip/jobs/341401839
- https://travis-ci.org/mirage/mirage-tcpip/jobs/341401841
- https://travis-ci.org/mirage/mirage-tcpip/jobs/341401842

For https://github.com/mirage/mirage-tcpip/pull/350 I see

```
===== ∗  10   ↻  14 =====
Fatal error: exception File "src/ci_opam.ml", line 116, characters 36-42: Assertion failed
```
which comes from https://github.com/ocaml/ocaml-ci-scripts/blob/84971b08f4a80a5e018035ffd5e1a1c0ee63568b/src/ci_opam.ml#L116

I'm sure the root cause is elsewhere but the error message isn't clear.

### PR DESCRIPTION
**Pull request by jpdeplaix**
I don't understand where the format I was parsing came from really. Is there several format outputted by ```opam --json``` ?

### CODE REVIEW

File: src/ci_opam.ml [hunk 1]
```diff
@@ -122,12 +122,16 @@ let get_package_versions_from_json file =
...
     let get_pkg_ver o =
-      str (List.assoc "name" o) ^ "." ^ str (List.assoc "version" o)
+      let name = str (List.assoc "name" o) in
+      if String.equal name pkg_name then
+        []
+      else
+        let version = str (List.assoc "version" o) in
+        [name ^ "." ^ version]
     in
     let get_install o = get_pkg_ver (obj (List.assoc "install" o)) in
```
Comment (samoht) [inline src/ci_opam.ml]: `"install"` can also be missing, e.g.

```
$ opam remove ocamlfind --json foo.json --dry-run` ça donne:
[
  [
    {
      "delete": {
        "name": "result",
        "version": "1.3"
      }
    },
    {
      "delete": {
        "name": "ocaml-migrate-parsetree",
        "version": "1.0.7"
      }
    },
    {
...
```
